achievements/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$',views.achievements, name = "achievements"),

]

contactUs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.contactUs, name='contactUs')
];

jpps/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^ckeditor/upload/', include('ckeditor_uploader.urls')),
    #url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    #url(r'jet/', include('jet.urls')),
    url(r'admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    url(r'^Gallery/', include('galleryApp.urls', namespace='galleries')),
    url(r'^news/',include('newsApp.urls', namespace='news')),
    url(r'^staff/',include('staffApp.urls')),
    url(r'^facilities/',include('facilities.urls')),
    url(r'^achievements/',include('achievements.urls')),
    url(r'^registration/',include('registration.urls')),
    url(r'^vision/',include('vision.urls')),
    url(r'^contactus/',include('contactUs.urls')),
    url(r'^onlinelearning/',include('onlineLearning.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

newsApp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$',views.All, name = "All"),
    url(r'(?P<slug>[-\w]+)/$',views.article_detail, name = "detail"),
    
    #include('djadmin.urls')),

]

vision/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.vision, name='vision')
];

achievements/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from .validators import validate_file_extension_coverImage


class coverImage(models.Model):
    cover = models.ImageField(upload_to='Cover/',verbose_name="عکس پشت تیتر",null=True)
    
    def __str__(self):
        return "عکس پشت تیتر"

    class Meta:
        verbose_name = "عکس پشت تیتر"
        verbose_name_plural = "عکس پشت تیتر"
    
        
class achievement(models.Model):
    title = models.CharField(max_length = 64, null = True ,verbose_name="تیتر به انگلیسی")
    slug = models.SlugField(max_length=140, unique=True, null =True, editable= False)
    farsiTitle = models.CharField(max_length = 64, null = True, verbose_name="تیتر به فارسی")
    shortDescription = models.TextField(max_length = 400, null = True, verbose_name="خلاصه به انگلیسی")
    farsiShortDescription = models.TextField(max_length = 400, null = True,  verbose_name="خلاصه به فارسی")
    image = models.ImageField( upload_to='achievements/', verbose_name="عکس کاور", validators = [validate_file_extension_coverImage])
    description = RichTextUploadingField(config_name='awesome_ckeditor', null = True,  verbose_name="توضیحات به انگلیسی")
    farsiDescription = RichTextUploadingField(config_name='awesome_ckeditor', null = True, verbose_name="توضیحات به فارسی")

    class Meta:
        verbose_name = "دستاورد"
        verbose_name_plural = "دستاوردها"

    def __str__(self):
        return self.farsiTitle
    
    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while achievement.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

@receiver(pre_save, sender=achievement, dispatch_uid='slugify3')
def generateSlug(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = instance._get_unique_slug()

contactUs/models.py
from django.db import models

class coverImage(models.Model):
    cover = models.ImageField(upload_to='Cover/',verbose_name="عکس پشت تیتر",null=True)
    
    def __str__(self):
        return "عکس پشت تیتر"
    
    class Meta:
        verbose_name = "عکس پشت تیتر"
        verbose_name_plural = "عکس پشت تیتر"

class workRequest(models.Model):
    Name = models.CharField(max_length = 64, verbose_name = "نام")
    familyName = models.CharField(max_length = 64, verbose_name = "نام خانوادگی")
    fatherName = models.CharField(max_length = 64, verbose_name = "نام پدر")
    idNumber = models.CharField(max_length = 32,verbose_name = "شماره کد ملی")
    bsNumber = models.CharField(max_length = 32,verbose_name="شماره شناسنامه")
    dateOfBirth = models.CharField(max_length = 16, verbose_name="تاريخ تولد")
    placeofbirth = models.CharField(max_length = 64, verbose_name = "محل صدور شناسنامه")
    married = models.CharField(max_length = 64, verbose_name = "وضعیت تاهل")
    lastGraduate = models.CharField(max_length = 64, verbose_name = "آخرین مدرک تحصیلی")
    major = models.CharField(max_length = 64, verbose_name = "رشته", blank = True)
    employment = models.CharField(max_length = 64, verbose_name = "نوع استخدام", blank = True)
    employmentDate = models.CharField(max_length = 64, verbose_name = "تاریخ استخدام", blank = True)
    organizationUnit = models.CharField(max_length = 64, verbose_name = "واحد سازمانی", blank = True)
    district = models.CharField(max_length = 24, verbose_name = "منطقه", blank = True)
    background = models.CharField(max_length = 256, verbose_name = "سوابق خدمتی", blank = True)
    englishLevel = models.CharField(max_length = 12, verbose_name = "تسلط بر زبان انگلیسی", blank = True)
    computerSkills = models.CharField(max_length = 12, verbose_name = "تسلط بر کامپیوتر", blank = True)
    smartBoardSkills = models.CharField(max_length = 12, verbose_name = "تسلط بر تخته هوشمند", blank = True)
    otherSkills = models.CharField(max_length =256, verbose_name = "مهارت های دیگر", blank = True)
    grade = models.CharField(max_length = 256, verbose_name = "علاقه مند به تدریس پایه", blank = True)
    #recomendations
    firstName = models.CharField(max_length = 64, verbose_name = "نام" , blank = True)
    firstFamilyName =  models.CharField(max_length = 64, verbose_name = "نام خانوادگی", blank = True)
    firstAddress = models.CharField(max_length = 256, verbose_name = "آدرس منزل یا محل کار با تلفن", blank = True)
    secondName = models.CharField(max_length = 64, verbose_name = "نام" , blank = True)
    secondFamilyName =  models.CharField(max_length = 64, verbose_name = "نام خانوادگی", blank = True)
    secondAddress = models.CharField(max_length = 256, verbose_name = "آدرس منزل یا محل کار با تلفن", blank = True)
    other = models.CharField(max_length = 128, verbose_name = "توضیحات", blank = True)
    class Meta:
        verbose_name ="درخواست همکاری"
        verbose_name_plural ="درخواست های همکاری"
    def __str__(self):
        return (self.Name + " " + self.familyName)

onlineLearning/models.py
# -*- coding: utf-8 -*-
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from .validators import validate_file_extension
# Create your models here.

class recourse(models.Model):
    name = models.CharField(max_length = 64, verbose_name = "اسم", null = True)
    File = models.FileField(verbose_name = "فایل", null = True, validators = [validate_file_extension])
    def __str__(self):
         return self.name
    class Meta:
        verbose_name = "منابع"
        verbose_name_plural = "منابع"



class coverImage(models.Model):
    cover = models.ImageField(upload_to='Cover/',verbose_name="عکس پشت تیتر",null=True)

    def __str__(self):
        return "عکس پشت تیتر"
 
 
    class Meta:
        verbose_name = "عکس پشت تیتر"
        verbose_name_plural = "عکس پشت تیتر"
    
class content(models.Model):
    title = models.CharField(max_length = 64, verbose_name="تیتر به انگلیسی")
    farsi_title = models.CharField(max_length = 64, verbose_name="تیتر به فارسی")
    description = RichTextUploadingField(config_name='awesome_ckeditor', verbose_name="توضیحات به انگلیسی")
    farsi_description = RichTextUploadingField(config_name='awesome_ckeditor', verbose_name="توضیحات به فارسی")
    def __str__(self):
        return self.farsi_title
    class Meta:
        verbose_name = "محتوی"
        verbose_name_plural = "محتوی"

vision/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class coverImage(models.Model):
    cover = models.ImageField(upload_to='Cover/',verbose_name="عکس پشت تیتر",null=True)

    def __str__(self):
        return "عکس پشت تیتر"

    class Meta:
        verbose_name = "عکس پشت تیتر"
        verbose_name_plural = "عکس پشت تیتر"
        
class content(models.Model):
    title = models.CharField(max_length = 64, verbose_name="تیتر به انگلیسی")
    farsi_title = models.CharField(max_length = 64, verbose_name="تیتر به فارسی")
    description = RichTextUploadingField(config_name='awesome_ckeditor', verbose_name="توضیحات به انگلیسی")
    farsi_description = RichTextUploadingField(config_name='awesome_ckeditor', verbose_name="توضیحات به فارسی")
    def __str__(self):
        return self.farsi_title
    class Meta:
        verbose_name = "محتوی"
        verbose_name_plural ="محتوی"

achievements/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.core.exceptions import ObjectDoesNotExist

from .models import achievement,coverImage


def achievements(request):
    try:
        cover = coverImage.objects.latest('id')
    except ObjectDoesNotExist:
        cover = None
    try:
        All_achievement = achievement.objects.all().order_by('-id')
    except ObjectDoesNotExist:
        All_achievement = None
    context = {
        'achievements' : All_achievement,
        'cover' : cover,
    }
    return render(request, 'achievements.html', context)

contactUs/views.py
import json
import urllib.request as reqq
import urllib

from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from .models import workRequest,coverImage
from django.views.decorators.csrf import csrf_exempt


def contactUs(request):
    if request.method == 'POST':
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req =  reqq.Request(url, data=data)
        response = reqq.urlopen(req)
        result = json.loads(response.read().decode())
        #getting values from post
        name = request.POST.get('applicantname')
        familyName = request.POST.get('applicantlastname')
        idNumber = request.POST.get('idnumber')
        bsNumber = request.POST.get('bsnumber')
        placeofbirth = request.POST.get('placeofbirth')
        bssnumber = request.POST.get('bssnumber')
        dateofbirth = request.POST.get('dateofbirth')
        fathername = request.POST.get("applicantfathername")
        marriageStatus = request.POST.get("marriagestatus")
        edulevel = request.POST.get("edulevel")
        major = request.POST.get("major")
        contracttype = request.POST.get("contracttype")
        contractdate = request.POST.get("contractdate")
        orgname = request.POST.get("orgname")
        orgdistrict = request.POST.get("orgdistrict")
        workxp = request.POST.get("workxp")
        englishlvl = request.POST.get("englishlvl")
        computerlvl = request.POST.get("computerlvl")
        smartboard = request.POST.get("smartboard")
        otherskills = request.POST.get("otherskills")
        intrestedgrade = request.POST.get("intrestedgrade")
        nameintroducer1 = request.POST.get("name-introducer-1")
        lastnameintroducer1 = request.POST.get("lastname-introducer-1")
        addressintroducer1 = request.POST.get("address-introducer-1")
        nameintroducer2 = request.POST.get("name-introducer-2")
        lastnameintroducer2 = request.POST.get("lastname-introducer-2")
        addressintroducer2 = request.POST.get("address-introducer-2")
        othernotes = request.POST.get("othernotes")
        #adding the values in a context variable 
        #returing the template 
        newform = workRequest(
            Name = name,
            familyName = familyName,
            fatherName = fathername,
            idNumber = idNumber,
            bsNumber = bsNumber,
            dateOfBirth = dateofbirth,
            placeofbirth = placeofbirth,
            married = marriageStatus,
            lastGraduate = edulevel,
            major = major,
            employment = contracttype,
            employmentDate = contractdate,
            organizationUnit = orgname,
            district = orgdistrict,
            background = workxp,
            englishLevel = englishlvl,
            computerSkills = computerlvl,
            smartBoardSkills = smartboard,
            otherSkills = otherskills,
            grade = intrestedgrade,
            #recomendations
            firstName = nameintroducer1,
            firstFamilyName =  lastnameintroducer1,
            firstAddress = addressintroducer1,
            secondName = nameintroducer2,
            secondFamilyName =  lastnameintroducer2,
            secondAddress = addressintroducer2,
            other = othernotes
        )
        if result['success']:
            try:
                cover = coverImage.objects.latest('id')
            except ObjectDoesNotExist:
                cover = None
            context = {
                'cover' : cover,
            }
            return render(request, 'submitmessage.html', context)
        else:
            try:
                cover = coverImage.objects.latest('id')
            except ObjectDoesNotExist:
                cover = None
            context = {
                'cover' : cover,
            }
            return render(request, 'formerror.html', context)
    else:
        try:
            cover = coverImage.objects.latest('id')
        except ObjectDoesNotExist:
            cover = None
        context = {
            'cover' : cover,
        }
        return render(request, 'contactus.html', context)

onlineLearning/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.core.exceptions import ObjectDoesNotExist

from .models import content,coverImage
def onlineLearning(request):
    try:
        contents = content.objects.latest('id')
    except:
        contents = None
    try:
        cover = coverImage.objects.latest('id')
    except ObjectDoesNotExist:
        cover = None
    context = {
        'content' : contents,
    }
    
    return render(request, 'onlinelearning.html', context)

vision/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

from .models import content,coverImage
def vision(request):
    try:
        contents = content.objects.latest('id')
    except ObjectDoesNotExist:
        contents = None
    try:
        cover = coverImage.objects.all().order_by('id')[0]
    except:
        cover = None
    context = {
        'cover' : cover,
        'content' : contents,
    }
    
    return render(request, 'vision.html', context)

templates/UnderConstruction.html
<!DOCTYPE html>

{% load static %}
<head>
  <meta charset="utf-8">
  <title>Undrer Construction | در دست ساخت</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/bs/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/MasterFinal.css' %}">
  <link rel="stylesheet" href="{% static 'css/neededtelegram.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Lalezar&amp;subset=arabic" rel="stylesheet">
  <script src="{% static 'js/bs/jquery.min.js' %}"></script>
  <script src="{% static 'js/bs/popper.min.js' %}"></script>
  <script src="{% static 'js/bs/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/getCheckCookie.js' %}"></script>
  <style media="screen">
    .underConstTape {
      border: 4px dashed yellow;
      height: 75px;
      margin: 15px -200px;
      font-size: 40px;
      text-align: center;
      transform: rotate(-10deg);
      vertical-align: middle;
    }
  </style>
</head>

<body onload="checkCookie()">
  <button onclick="topFunction()" class="farsialignment" id="goToTopBtn" title="Go to top">
    <span class="english"> UP</span><span class="farsi"> بالا</span>
    <img src="{% static 'img/chevron-top.svg' %}" alt="" width="15px">
  </button>
  <!--Fixed top navbar-->
  <nav class="sticky-top farsialignment navbar navbar-expand-lg navbar-orgcolor bg-orgcolor">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navContent navbar-collapse" style="flex-grow:0 !important;-webkit-flex-grow: 0 !important;">
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href={% url 'Home' %}><img src="{% static 'img/webicon/Blue Outline Version/home-W.png' %}" alt="home page" width="40px"></a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{% static 'img/webicon/Blue Outline Version/about-W.png' %}" alt="" width="30px"><span class="english">About</span><span class="farsi">درباره ما</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href={% url 'vision' %}><span class="english">Vision</span><span class="farsi">اهداف</span></a>
              <a class="dropdown-item" href={% url 'achievements' %}><span class="english">Achievements</span><span class="farsi">دستاورد ها</span></a>
              <a class="dropdown-item" href={% url 'facilities' %}><span class="english">Facilities</span><span class="farsi">امکانات</span></a>
              <a class="dropdown-item" href={% url 'staff' %}><span class="english">Staff</span><span class="farsi">همکاران</span></a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'news:All' %}><img src="{% static 'img/webicon/Blue Outline Version/news-W.png' %}" alt="" width="30px"><span class="english">News</span><span class="farsi">اخبار</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'galleries:All' %}><img src="{% static 'img/webicon/Blue Outline Version/gallery-W.png' %}" alt="" width="30px"><span class="english">Gallery</span><span class="farsi">گالری</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'registration' %}><img src="{% static 'img/webicon/Blue Outline Version/Rprogram-W.png' %}" alt="" width="30px"><span class="english">Registration</span><span class="farsi">ثبت نام</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'contactUs' %}><img src="{% static 'img/webicon/Blue Outline Version/iphone-W.png' %}" alt="" width="30px"><span class="english">Contact Us</span><span class="farsi">تماس با ما</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'onlineLearning' %}><img src="{% static 'img/webicon/Blue Outline Version/Onlinelearning-W.png' %}" alt="" width="30px"><span class="english">Online Learning</span><span class="farsi">آموزش از راه دور</span></a>
          </li>
          <li class="nav-item">
            <a id="loginbuttonnobodypage" class="nav-link" href="http://lms-javid.ir/login/index.php">
            <button id="loginbutton"type="button" class="btn btn-outline-white" onmouseover="imghover(myimg);" onmouseout="imgunhover(myimg);">
              <div class="navbar-link">
                <img id="myimg" src="{% static 'img/webicon/Blue Outline Version/Lock.png' %}" alt="" width="30px"><span class="english"> E-learning Section</span><span class="farsi">بخش آموزش</span>
              </div>
            </button>
        </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <header>
    <!--banner & logo and Page title-->
    <div style="align-items: center; position: relative">
      <div id="DiscOverImg">
        <h1 class="english">Under Construction</h1>
        <h1 class="farsi" style="text-align: center !important">در دست ساخت</h1>
        <p class="english"></p>
        <p class="farsi" style="text-align: center !important"></p>
      </div>
      <img id="fitImg" src="{% static 'img/banner.png' %}" alt="BannerImage">
      <div id="logoOverlap">
        <img class="imglogo" src="{% static 'img/JPPS Logo HQ.png' %}" alt="Logo Image">
      </div>
  </header>

  <div class="container maincommenbody" style="overflow: hidden;">
    <div style="padding: 100px 0px;">
      <p class="underConstTape" style="font-family: 'Lato';">Under Construction</p>
      <p class="underConstTape" style="font-family: 'Lalezar';">در دست ساخت</p>
      <p class="english" style="text-align: center; margin:40px 0px;">Sorry for inconvenience</p>
      <p class="farsi" style="text-align: center; margin:40px 0px;">بابت عدم آمادگی متاسف هستیم</p>
    </div>
  </div>



  <footer id="footerAttr">
    <div class="container-fluid row">
      <!--Footer 1st colomn-->
      <div class="container col-xl-4 col-lg-4 col-md-6 col-sm-12">
        <h3 class="english">Find us here!</h3>
        <h3 class="farsi" style="text-align:center">ما را اینجا پیدا کنید!</h3>
        <div id="map"></div>
        <div class="english" style="text-align:Left;width:300px;margin-right:auto;margin-left:auto">
          <b>Address:</b> NJLDLC, Derakhshani St, Ashrafi Esfahani Expy, Tehran, Iran.
        </div>
        <div class="farsi" style="text-align:right;width:300px;margin-right:auto;margin-left:auto">
          <b>آدرس: </b>تهران، بزرگراه اشرفی اصفهانی، کوچه درخشانی، دبستان غیر دولتی جاوید
        </div>
        <script>
          function initMap() {
            var mapboarder = {
              lat: 35.744124,
              lng: 51.336588
            };
            var markerr = {
              lat: 35.744255,
              lng: 51.334723
            };
            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 16,
              center: markerr
            });
            var marker = new google.maps.Marker({
              position: mapboarder,
              map: map
            });
          }
        </script>
        <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAPodOx_4C8n3TrzngrizGFUAm--Dgav7o&callback=initMap">
        </script>
      </div>
      <!--Footer 2nd colomn-->
      <div class="container col-xl-4 col-lg-4 col-md-6 col-sm-12">
        
        <h3 class="english">Message us here!</h3>
        <h3 class="farsi" style="text-align:center">اینجا به ما پیام دهید!</h3>
        <!-- TELEGRAM PART-->
        <div class="telegramDiv">
          <div class="tgme_page">
            <div class="tgme_page_photo">
                <a href="tg://resolve?domain=javid_25">
                    <img class="tgme_page_photo_image" src="{% static 'img\javid_telegram.jpg' %}"></a>
              </a>
              
            </div>
            <div class="tgme_page_title">Javid School</div>
            <div class="tgme_page_extra">
              @javid_25
            </div>
            <div class="tgme_page_description">پیش دبستان ودبستان پسرانه غیردولتی جاوید- منطقه 2 تهران - تأسیس 1370</div>
            <div class="tgme_page_action">
              <a class="tgme_action_button_new" href="tg://resolve?domain=javid_25">Send Message</a>
            </div>
            <!-- WEBOGRAM_BTN -->
            <div class="tgme_page_additional">
              If you have
              <strong>Telegram</strong>, you can contact
              <br>
              <strong>Javid</strong> right away.
            </div>
          </div>
        </div>
      </div>
      <!--Footer 3rd colomn-->
      <div class="container col-xl-4 col-lg-4 col-md-12 col-sm-12">
        
        <h3 class="farsi" style="text-align:center">!Change the Language Here</h3>
        <h3 class="english" style="text-align:center">!اینجا زبان را تغییر دهید</h3>
        <div class="btn-group" style="margin-top:8px;">
          
          <button type="button" class="btn btn-outline-white dropdown-toggle" data-toggle="dropdown">
            <span class="english">Site Language</span>
            <span class="farsi">زبان سایت</span>
          </button>
          <div class="dropdown-menu">
            <button class="dropdown-item" onclick="changelang2fa()">
                <img style="width:20px"src="{% static 'img/ir.svg' %}" alt="ir-icon"> فارسی</button>
            <button class="dropdown-item" onclick="changelang2en()">
                <img style="width:20px"src="{% static 'img/gb.svg' %}" alt="ir-icon"> English</button>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!--copyright-->
  <div id="copyright">
    | Designed & Developed by
    <a href="https://www.linkedin.com/in/imananoosheh/">Iman Anoosheh</a> &
    <a href="https://www.linkedin.com/in/ali-yazdanpanah-5a7b10146">Ali Yazdanpanah</a> © 2018 | All rights reserved. |
  </div>

  <script type="text/javascript" src="{% static 'js/masterfinal.js' %}"></script>
</body>

</html>